version: '3.7'

services:
  
  irc:
    image: irc:${TAG}
    build: 
      context: ./requirements/irc
      args:
        - REPO=${REPO}
    container_name: irc
    restart: always
    ports: ['6667:6667']
    networks: ['irc_network']

networks:
  irc_network:
    name: irc_network
